# Generated by Django 2.1.1 on 2018-12-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assi_title', models.CharField(max_length=100)),
                ('assi_due_date', models.DateTimeField(verbose_name='Due Date')),
                ('assi_description', models.CharField(default='', max_length=500)),
                ('assi_event_id', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='', max_length=100)),
                ('course_num', models.CharField(default='', max_length=10)),
                ('course_key', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=30)),
                ('stud_calendar', models.CharField(default='', max_length=200)),
                ('stud_blacklist', models.ManyToManyField(to='assignment_scheduler.Assignment')),
                ('stud_course', models.ManyToManyField(to='assignment_scheduler.Course')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assi_course',
            field=models.ManyToManyField(to='assignment_scheduler.Course'),
        ),
    ]
